[meta]
name        = "Friday Night Funkin' Rewritten"
author      = "HTV04"
description = "Rewrite of Friday Night Funkin' built on LÖVE"
version     = "1.0.0-switch"

[pre_hook]
clean = false

[build]
icon_file        = "resources/switch-icon"
source_directory = "src/love"
build_directory  = "build/switch"
love_directory   = false
targets          = ["switch"]
output_to_build  = true
target_name      = "funkin-rewritten"
is_raw           = false
